#ifndef LLVM_PROFILEDATA_COPYPROFREADER_H
#define LLVM_PROFILEDATA_COPYPROFREADER_H

#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/DebugInfo/Symbolize/SymbolizableModule.h"
#include "llvm/DebugInfo/Symbolize/Symbolize.h"
#include "llvm/Object/Binary.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/ProfileData/CopyProfData.inc"
#include "llvm/ProfileData/MemProf.h" // Reuse Frame
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/MemoryBuffer.h"

namespace llvm::copyprof {

// Reads and symbolizes CopyProf report files.
// The raw profile contains a header, a sequence of Report entries, memory
// segment mappings, and stack traces. Use \c create() to construct a reader,
// then call \c readAndSymbolize() to resolve stack traces and \c printYAML()
// to emit the results.
class LLVM_ABI RawCopyProfReader {
public:
  struct SymbolizedReport {
    uint64_t CopyNumBytes;
    SmallVector<memprof::Frame> CallStack;
  };

  RawCopyProfReader(const RawCopyProfReader &) = delete;
  RawCopyProfReader &operator=(const RawCopyProfReader &) = delete;
  ~RawCopyProfReader();

  // Returns true if the given buffer contains a raw CopyProf profile.
  static bool hasFormat(const MemoryBuffer &DataBuffer);
  // Returns true if the file at the given path contains a raw CopyProf profile.
  static bool hasFormat(const StringRef Path);

  // Instaniates a `RawCopyProfReader` to print the reports from `ProfilePath`.
  // The profile must have been generated by `ProfiledBinary`.
  static Expected<std::unique_ptr<RawCopyProfReader>>
  create(const Twine &ProfilePath, StringRef ProfiledBinary);
  // Performs the actual processing and symbolizes stack traces.
  Error readAndSymbolize();
  // Outputs the processed reports. `readAndSymbolize` must have been called
  // beforehand.
  void printYAML(raw_ostream &OS, bool Demangle = false);

private:
  RawCopyProfReader(object::OwningBinary<object::Binary> &&Bin,
                    std::unique_ptr<MemoryBuffer> ProfileBuffer)
      : Binary(std::move(Bin)), ProfileBuffer(std::move(ProfileBuffer)) {}

  Error initialize();
  Error readRawProfile();
  Error setupForSymbolization();
  Error symbolizeAndFilterStackFrames(
      std::unique_ptr<llvm::symbolize::SymbolizableModule> Symbolizer);

  object::SectionedAddress getModuleOffset(uint64_t VirtualAddress);

  object::OwningBinary<object::Binary> Binary;
  std::unique_ptr<MemoryBuffer> ProfileBuffer;

  // Version of raw copyprof binary currently being read.
  uint64_t CopyProfRawVersion = RawVersion;
  // The preferred load address of the executable segment.
  uint64_t PreferredTextSegmentAddress = 0;
  // The base address of the text segment in the process during profiling.
  uint64_t ProfiledTextSegmentStart = 0;
  // The limit address of the text segment in the process during profiling.
  uint64_t ProfiledTextSegmentEnd = 0;

  // The memory mapped segment information for all executable segments in the
  // profiled binary.
  llvm::SmallVector<SegmentEntry, 2> SegmentInfo;

  // Map from stack id to vector of PCs.
  llvm::DenseMap<uint64_t, llvm::SmallVector<uint64_t>> StackMap;

  // Cached symbolization from PC to Frame.
  llvm::DenseMap<uint64_t, llvm::SmallVector<memprof::Frame>> SymbolizedFrame;

  // List of reports read from the report file.
  std::vector<Report> Reports;

  // List of symbolized reports.
  std::vector<SymbolizedReport> SymbolizedReports;
};

} // namespace llvm::copyprof

#endif // LLVM_PROFILEDATA_COPYPROFREADER_H
